name: Validate with HACS

on:
  push:
    branches:
      - "**"
  pull_request:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration
